name: Build Flutter Minesweeper

on:
  push:
    tags:
      - 'v*'  # Запуск при пуше тега вида v1.0.0
  workflow_dispatch: # Возможность запустить вручную

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Enable desktop
        run: flutter config --enable-${{ matrix.os == 'windows-latest' && 'windows' || (matrix.os == 'ubuntu-latest' && 'linux' || 'macos') }}-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build app
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            flutter build windows --release
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update && sudo apt-get install -y libgtk-3-dev
            flutter build linux --release
          else
            flutter build macos --release
          fi

      - name: Archive build
        run: |
          mkdir artifacts
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a artifacts/minesweeper-windows.zip build/windows/x64/runner/Release/*
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            tar -czvf artifacts/minesweeper-linux.tar.gz -C build/linux/x64/release/bundle .
          else
            tar -czvf artifacts/minesweeper-macos.tar.gz -C build/macos/Build/Products/Release Minesweeper.app
          fi

      - name: Upload artifacts

        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: artifacts/*

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
