name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        shell: bash
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.35.1 --depth 1 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Check Flutter version
        run: flutter --version
        shell: bash

      - name: Enable web
        run: flutter config --enable-web
        shell: bash

      - name: Prepare deploy script
        run: chmod +x .github/workflows/deploy.sh
        shell: bash

      - name: Compute base href
        id: compute_base
        shell: bash
        run: |
          REPO_NAME=$(basename "$GITHUB_REPOSITORY")
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Install dependencies and build web
        shell: bash
        run: .github/workflows/deploy.sh "$REPO_NAME"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web


